### ISSUE TITLE
Missing icons. Firefox 63

### ISSUE THREAD

**Issue by radjah** [kumabook/stickynotes#110]
![clipboard](https://user-images.githubusercontent.com/1141613/48312580-07147f00-e5c2-11e8-9f16-f8fe80f1b0e6.png)
Gray square is the result of mouse hovering.
Inside the add-on file the necessary images are present. (sticky@filenamezero.dip.jp.xpi\content_scripts)
I tried to create notes on different sites and on a clean profile.

**Comment by kumabook** [comment]
Thank you for reporting.

That is because detection of browser type (chrome or firefox).
I changed the detection and release it at 1.1.6.

thanks
