### ISSUE TITLE
A separate toolbar button to create a note

### ISSUE THREAD

**Issue by wrooot** [kumabook/stickynotes#114]
It would be more convenient to have a separate button on a toolbar to generate a note than having to go through a menu. I would even prefer that to having Sticky Notes entry in page's context menu.

**Comment by kumabook** [comment]
Thank you for feedback!
Sadly, a addon can have only one toolbar button.
So, I'm planning to add address bar button instead.
What do you thing this alternative plan?

<img width="975" alt="screen shot 2019-02-11 at 21 11 50" src="https://user-images.githubusercontent.com/753703/52562479-f930fd00-2e41-11e9-914a-313c5c579799.png">

**Comment by wrooot** [comment]
I guess that is still better than having to dig through context menus. Thanks.

**Comment by kumabook** [comment]
I released as version 1.2.0

**Comment by wrooot** [comment]
It works. Thanks! I would donate a few bucks here and then if you'd have such donating option ;)
