### ISSUE TITLE
New sticky from context menu not working on Youtube

### ISSUE THREAD

**Issue by wrooot** [kumabook/stickynotes#116]
It seems that to create a sticky on Youtube page i must use toolbar icon and right clicking and using context menu doesn't work.

**Comment by kumabook** [comment]
Sorry for inconvenience. 
Context menu doesn't work after transition on some page (YouTube, gmail).

I fixed it as version 1.2.1 (that is released just now)

**Comment by wrooot** [comment]
Thanks. Tried 1.2.2. It's fixed.
