### ISSUE TITLE
Inserting tab stop in text?

### ISSUE THREAD

**Issue by fschwarz19** [kumabook/stickynotes#118]
Is it possible to capture tab key stroke to insert a tab stop in text and not change focus to other Firefox GUI elements?
Tab stop would be very useful to arrange lists better.

**Comment by kumabook** [comment]
Hi, thank you for feedback.

It is possible that you insert a tab stop instead of changing focus.
However I think tab key should change focus by default.
So, you can customize tab-key action inside textarea.

**Comment by fschwarz19** [comment]
Hi, thank you for answering.

How am I able to customize? Do you mean by an option in your addon or firefox. Or by coding?

**Comment by kumabook** [comment]
I implemented as 1.1.9 (released just now).

**Comment by fschwarz19** [comment]
Great, thanks! :)
