### ISSUE TITLE
On Premise Sticky Notes server

### ISSUE THREAD

**Issue by Utopism** [kumabook/stickynotes#131]
Hi, is there is a way to install hour own Sticky Notes server ?
It's for a personal use.

Sticky Notes is a really useful tool !

Thanks a lot.

**Comment by kumabook** [comment]
Sorry for the late reply.

The answer is possible, but currently it needs a lot of work.

1. Create you own backend server from https://github.com/kumabook/stickynotes-backend
2. Create client id and secret. The backend server uses `https://github.com/doorkeeper-gem/doorkeeper` gem. You can create client id and key with `/oauth/applications/new` path.
2. Create you own webextension based on this repository
3. Build you own extension with environment values that uses your backend

```

export BASE_URL= https://your.backend.url
#export https://stickynotes.kumabook.tokyo
export CLIENT_ID=YOUR_BACKEND_CLIENT_ID
export CLIENT_SECRET=YOUR_BACKEND_CLIENT_SECRET
export SYNC_INTERVAL=30000

export VERSION=1.2.4
```

**Comment by Utopism** [comment]
Hi @kumabook, I have now my own backend server running, thank a lot for that, it's very nice to you to have published the source code.
I have to see how to create my own extension now !

**Comment by Utopism** [comment]
We can close this issue as I succeded creating my own on premise server. I have been using it for a while now !

**Comment by Utopism** [comment]
Closing it.
