### ISSUE TITLE
Reseting password

### ISSUE THREAD

**Issue by Bobothegypsy** [kumabook/stickynotes#150]
hello hello,

Love your stickies but I'm having a wee bit of an issue, I can't reset my password. I enter my email and it first says "We're sorry, but something went wrong." and then if I go back and try again it says "Instructions have been sent to your email." but I never receive them.

can I get a little help with this?

Thanks,

Chris

**Comment by kumabook** [comment]
Sorry, I fixed the mail problem, please try again.

**Comment by Bobothegypsy** [comment]
Thanks so much for you quick action on this! It worked.

Take care,

C
