### ISSUE TITLE
message suggestion for delete function confirmation (minor issue)

### ISSUE THREAD

**Issue by JimWinters** [kumabook/stickynotes#28]
When I click on the X on the sticky, I get a popup dialog that says

    Are you sure to delte the sticky?

    Confirm before delete a sticky.

You might like to change that to

    Are you sure you want to delete the sticky?     <-- also fixing "delte" typo

    Confirm before deleting a sticky.

Thank you.

**Comment by aHirokiKumamoto** [comment]
Thank you for your advice.
I fixed wording at version 0.7.6.
