### ISSUE TITLE
problems when using with Gmail

### ISSUE THREAD

**Issue by JimWinters** [kumabook/stickynotes#29]
I installed stickynotes hoping to use it with Gmail.  In particular, I hoped I would be able to put a sticky note on an individual message and have that sticky note appear again when I open that message again.

I am able to put a sticky note on the Gmail page, but it appears on every page in Gmail: the message summary and every message.

I understand it may be difficult or impossible to do what I want, but I thought I would ask.  I might still use stickynotes on other web sites.

Also, the stickies don't scroll as I would want in Gmail.  In the summary page or in a message page, when I scroll, the sticky stays in the same place on the screen.  Perhaps this is because Gmail is scrolling only part of the page (the scroll bar does not extend over the whole page).  Or perhaps it is a problem with the Gmail page in particular.  Again, I don't know how hard this might be to fix.  I notice that the stickies scroll fine on other sites where the scroll bar extends over the whole page (like this page where I am entering this issue).  I see that when I place a sticky on this text entry area (where I am entering this issue), which has its own scroll bar, that the sticky scrolls with the whole page, not with the text area, so maybe this has more to do with scrolled areas inside the page and does not have anything to do with the Gmail page in particular.

(And I'm being bad for putting two issues in one report.  Sorry.)

I'm using Firefox on Windows 7.

Thank you.

**Comment by kumabook** [comment]
@JimWinters Sorry for replying late and thank you for your reporting.
I'm trying to implement first topic.
It works on my environment at gmail page.
If you still use stickynotes, Please try this version:

https://github.com/kumabook/stickynotes/releases/download/support_hashchange/stickynotes.xpi

**Comment by kumabook** [comment]
@JimWinters 
And second topic is quite different from first topic and I think it's harder than first one.
I opened issue #35.
And I try to implement #35.
Thank you.

**Comment by JimWinters** [comment]
I installed the support_hashchange version and now I can put stickies on individual Gmail messages.  The stickies appear only when I am viewing the messages I put the stickies on.  Similarly, when I put a sticky on the summary page, it shows up only when I am on the summary page.  I didn't do extensive testing, but I tried it with several messages.

Nice.  :-)  Thank you for the fix.

**Comment by kumabook** [comment]
Thank you for your feedback!

I'm gonna check more, and if there is no problem, then release this feature.

Thanks.

**Comment by kumabook** [comment]
Stickies don't show when open new page. It is degrade
Fix degrade at 40fbb88

**Comment by kumabook** [comment]
Fix addon-sdk submodule version 224bb69

**Comment by kumabook** [comment]
Released as 0.8.0
