### ISSUE TITLE
sticky resize rarely works

### ISSUE THREAD

**Issue by ngnh** [kumabook/stickynotes#32]
First i didn't think you could resize until i occidentally managed to catch one that resized with no problems, but out of 20 stickies only one would resize.
Also it does not remember the size when page is reloaded.

**Comment by kumabook** [comment]
Thank you for reporting.

I reproduced the problem. I gonna fix it. 

Thanks you!

**Comment by kumabook** [comment]
Fixed at version 0.10.21
