### ISSUE TITLE
Sticky List sidebar suggestions

### ISSUE THREAD

**Issue by JimWinters** [kumabook/stickynotes#36]
1. In the sidebar, the dropdown menu says "dispaly (W)".  I think that you meant to say "display" or perhaps "Display".  Probably both "display" and "search" should be capitalized.

2. I don't know why the shortcut on the menu is W.  Usually I expect to see the shortcut be one of the letters in the label text.  (I can move keyboard focus to this control with Shift+Alt+W.)  Perhaps it is W to avoid some conflict with other GUI controls.  In that case, I guess there's nothing you can do about this.

3. Okay, this one is very minor.  :-)  The "display" menu items have what seem to me to be unfortunate shortcuts: t, s and t.  First, it is better if shortcuts are unique, although for non-unique shortcuts many toolkits will cycle through them, which is not too bad.  Second, because these letters appear in the word "List", that's where the underlines are, so the association with the desired words Tag and Site is reduced.  I don't have any great ways to solve this, but one possibility is to make the shortcuts be "1", "2" and "3", which don't have any association with the desired words at all (a disadvantage), but they are unambiguous and, I think, obvious.  But that might be a little ugly.  Perhaps you can come up with a much better solution.  But, as I said, this is very minor.

4. The search box is case sensitive.  I would prefer it to be case-insensitive.

These are just some suggestions for your consideration.  Thanks for your attention.

**Comment by kumabook** [comment]
Hi, thanks for your suggestion.


1 ... fix typo
2 ... I implemented customizable shortcut for `search` and `sidebar display options`.
Default shortcut:

|     command                |      shortcut            |
| -----------------------------  |  ---------------------  |
|search                           | control + shift + L |
|sidebar display options | control + shift + O |
----------------------------------------------------------

And you can custommize shourtcut from preferences.

3.  You are right. Two options have same access key.
I changed the button label `Display` ->  `Display by`
and changed options label and access key:
- Both tag and site (b),
- Site (s)
- Tag (t)

4. implemented  case-insensitive search

if you have time, Please check it out. 
https://github.com/kumabook/stickynotes/releases/download/improve_sidebar/stickynotes.xpi

Thanks.

**Comment by kumabook** [comment]
@JimWinters 

Thank you for your suggestions.

if you have time, Please check  https://github.com/kumabook/stickynotes/issues/36#issuecomment-97849637

**Comment by kumabook** [comment]
Released as 0.8.0

https://addons.mozilla.org/en-US/firefox/addon/sticky-notes/versions/?page=1#version-0.8.0
