### ISSUE TITLE
Generate sticky location on web page

### ISSUE THREAD

**Issue by Sillyme1** [kumabook/stickynotes#39]
When I generate a sticky, it may appear anywhere on the webpage - it does not appear in the same place every time.
I have seen in reviews that posters have generated a sticky, they say it appears in the sticky list but it is not on the page. I have found this too, but on searching the page, I find that it sometime is generated much wider than the width of the screen although the web page is screen width.

I am using a Lenove laptop 17", Windows 8.1,  with a resolution of 1366 x 768.

Regards

**Comment by kumabook** [comment]
Thank you for your feedback!

I'm sorry for your inconvenience.
If possible, please tell me the url.

This addon decides the position of new sticky with preceding mouse click position.
But it doesn't work on some pages that have complex structures or dynamic dom scripting.

I don't know the cause of that malfunction, but your feedback is the good clue.

**Comment by Sillyme1** [comment]
I've just tried a sticky on this page: X & Y - 1175   826. Only just on my screen in the bottom right corner. I'm running windows 8.1 on a lenove laptop, 15" screen, 1366 x 768 resoution. 

I also note that if I continue to generate stickies on the same page (still using this GitHub page) each new sticky moves to the left and a bit lower. Try it!

Just trying to help.

**Comment by kumabook** [comment]
Sorry for the delay in replying.

They are current specifications

- Shift the position of new sticky by `left:10` `top: 10` each new sticky.
- If the right or bottom position of new sticky  exceeds page size, then it expands page size.

Currently, I don't think they aren't the bugs. If you think they are bugs. Please tell me.

Thanks for your feedback!
