### ISSUE TITLE
Can't show entries on the firefox 40 of the windows 10

### ISSUE THREAD

**Issue by kuangdash** [kumabook/stickynotes#41]
I can't generate the notes……

**Comment by kuangdash** [comment]
Oh, I see it after having restarted browser……

**Comment by kumabook** [comment]
:ok_hand:

**Comment by kuangdash** [comment]
How about stick the entry to the DOM element? 

For your information: Let the entry attach to the nearest DOM element, then get the position of the DOM element and display the entry at the position. In this way, it can avoid the Size-Change of the browser.

**Comment by kuangdash** [comment]
Anyway, you can mark the entry as 'lost' and put it on the last position in case of DOM-Change

**Comment by kumabook** [comment]
Thank you for the suggestion!

I also think that's a good idea.

If it take a time to implement it, I try to implement.

**Comment by kumabook** [comment]
#35 is a similar issue
