### ISSUE TITLE
Tag not disappearing

### ISSUE THREAD

**Issue by aquay27** [kumabook/stickynotes#42]
Hi, I had created a tag for a webpage and it will not remove itself from the Sticky List after deleting the note. It also with not remove itself from the original tag even when a new tag replaces the original tag. Please help.

**Comment by kumabook** [comment]
Hi, thanks for reporting.

Please confirm somethings.

- Did you use a word `tag` as `sticky` or  `label(sticky category in white text box)` ?
- Did you delete the sticky from the `x` button?
- Does it causes any pages?
- Your environment (OS, firefox version)

Thanks

**Comment by aquay27** [comment]
Hi,
I created a label (sticky category in white text box). I have deleted it many times using the 'x' button. It causes the same page to reappear. I'm using Firefox.

**Comment by kumabook** [comment]
Hi,  I'm sorry that my reply to you is delayed.

Sorry, I haven't reproduce the problem yet. 

First, Can I ask more question?

- Is there stickynotes extesion logs in `Firefox menu -> Tools -> Web developer -> Browser Console`.
- Did you some special character?


Second,

I think you need to clean up the extension data. The steps below:

1. Backup sticky data. Use `export ` menu. save `stickynote_all.json`
2. Delete local database file `stickynotes.sqlite` in your firefox profile

for mac: `~/Library/Application\ Support/Firefox/Profiles/<profile name>/`
for windows:  `%APPDATA%\Mozilla\Firefox\Profiles\`

See: https://support.mozilla.org/ja/kb/profiles-where-firefox-stores-user-data

3. Restart firefox (stickynotes.sqlite regenerated)
4. import `stickynotes_all.json`



I'm sorry to trouble you

Thanks

**Comment by aquay27** [comment]
Thanks for the info but I resolved the problem by right clicking the label
and then deleting it to remove the sticky note.

**Comment by kumabook** [comment]
:ok_hand:
