### ISSUE TITLE
Feature request: Minimize/iconify notes

### ISSUE THREAD

**Issue by tonycpsu** [kumabook/stickynotes#43]
I'm looking at migrating to this extension from FloatNotes, which seems to have ceased development.  One feature it has that I like is that you can double-click the header minimize the note so it's just a small handle.  See [here](http://www.floatnotes.org/) under "Minimize notes" for what it looks like.

**Comment by kumabook** [comment]
@tonycpsu I implemented minimization feature at https://addons.mozilla.org/en-US/firefox/addon/sticky-notes/versions/0.10.6

Please check it out and feedback

**Comment by tonycpsu** [comment]
Very nice.  One nitpick: it's kind of hard to see the notes sometimes because the note color is so thin, see here:

![image](http://i.imgur.com/0X4Soxt.png)

**Comment by kumabook** [comment]
Thanks for your feedback.
You got a point.
I'm thinking what is the best looks for a minimized sticky the color of which can be changed.

Just a moment, please.

**Comment by kumabook** [comment]
adjust style of minimized icon at version 0.10.21
