### ISSUE TITLE
日経スマートチャートが表示されない

### ISSUE THREAD

**Issue by okbtsnr** [kumabook/stickynotes#58]
http://www.nikkei.com/markets/chart/#!/0101
移動平均線は問題ありませんが、一目均衡表が表示されません。
stickynotesを無効にすると問題なく表示されます。
調査方、よろしくお願いします。

**Comment by kumabook** [comment]
ご報告ありがとうございます。
現象の方確認しました。

修正の方も行いました。
0.10.7としてリリース予定で現在のmoziilaの審査中ですので、しばらく不便をかけるかもしれませんが、しばしお待ちください。

**Comment by okbtsnr** [comment]
早々の対応ありがとうございます。

**Comment by kumabook** [comment]
@okbtsnr 

0.10.7のレビューが終わりましたので、

https://addons.mozilla.org/en-US/firefox/addon/sticky-notes/versions/0.10.7

確認していただけると幸いです。

**Comment by kumabook** [comment]
大丈夫そうなので、closeします。
