### ISSUE TITLE
Sync not working

### ISSUE THREAD

**Issue by zendre4** [kumabook/stickynotes#64]
Hello,

The sync not working for me (use with login)

Thanks

**Comment by kumabook** [comment]
Thank you for reporting.
First, Could you try restart the firefox browsers.

**Comment by zendre4** [comment]
I try but this not solve the problem. Some notes appeared but other not appeared...

**Comment by kumabook** [comment]
Please open and login this page:

http://stickynotes-backend.herokuapp.com/login

after login, please check if there are some stickies and please tell me

**Comment by zendre4** [comment]
I view all notes here ! but for example the notes "Atteignez vos objectifs ! Effacer les autres sujets" (the first aqua notes) on my second navigator I view the text "Insert a note here"

**Comment by zendre4** [comment]
I test many times with my colleague, and we have some error... 

For example : I add a note, he has the note without content, or he has the note but the color is not the good (always yellow).

We try some solution : 

-Import/Export
-Delete the file stickynotes.sqlite on the firefox profile, restart firefox and start sync (with this solution I lost  ~ 50% of the notes...)

We found an other error : When I delete a note, on the backend the note still exist but his text is empty...

**Comment by kumabook** [comment]
Sorry for inconvenience.

Technically, each browser sync every 30 seconds, (for your case I think it is not suitable)
And if one sticky is edited by other app at the same time, latest change is applied.
But I have not fully check that app handle the situation.

This feature is now experimental, I try to improve this weekend.
Please wait.

**Comment by kumabook** [comment]
@zendre4 I fixed some bugs for sync and import function.
It should be improved.
And I also adjust sync interval from 30sec -> 10sec.
Please check it out.

Thanks

**Comment by zendre4** [comment]
It's work fine !  

There are still some bug (ex: when delete the sync is not good directly), but in general it works very well.

Thank you ! I will tell you if I have other bugs

**Comment by zendre4** [comment]
Sorry I forgot, they are a dialog box that appears when I edit a note, I don't now if it's normally...

**Comment by kumabook** [comment]
@zendre4  Thank you so much for your contribution.

Now, app shows confirm dialog if focused sticky is changed on server of other machine.
But sometime shows dialog when I don't expected (may be bug)
I try to fix it later.

Anyway, I appreciate you testing and using the app.

**Comment by kumabook** [comment]
> But sometime shows dialog when I don't expected (may be bug)

https://github.com/kumabook/stickynotes/issues/66

**Comment by zendre4** [comment]
@kumabook Thanks ! It's a great plugin, I search many time but this is the only plugin who proposes a sync.  Good job !
