### ISSUE TITLE
cannot change sticky's size if page is scrolled

### ISSUE THREAD

**Issue by pankona** [kumabook/stickynotes#74]
Hi. it seems I found an unexpected behavior of sticky.
i'm happy if you check my report below.

## Overview
* it seems the sticked sticky size is not able to change if a page that the sticky is sticked is scrolled.

## How to reproduce
* render arbitrary web page (page height is large enough to scroll)
* stick a sticky
* scroll page
* drag and drop a triangle placed at right-down corner of sticky to change sticky size

## Expected Result
* sticky size can be changed

## Actual Result
* sticky size doesn't change. the triangle moves around.

**Comment by kumabook** [comment]
Thanks for reporting!
I fixed it!. Please wait for next release

**Comment by pankona** [comment]
@kumabook 
thank you so much!
I'm looking forward to see next release! 🍶

**Comment by kumabook** [comment]
fixed on version 0.10.24
