### ISSUE TITLE
Can't move stickies since Nov 23 update.

### ISSUE THREAD

**Issue by y98iu00iu0f9** [kumabook/stickynotes#76]
Can't drag the stickies nor resize them since the last update.

Generating new stickies in new locations and closing the old ones as a work around.

**Comment by kumabook** [comment]
I'm so sorry.
Just my mistake.
I noticed it after released.
Fixed version is in review. Please wait a moment

**Comment by kumabook** [comment]
@y98iu00iu0f9 
I disabled version 0.10.23.
So, once you uninstall 0.10.23, you can install previous version 0.10.21.

Note: Uninstall stickynotes doesn't lose any data.

**Comment by kumabook** [comment]
version 0.10.24 released!

https://addons.mozilla.org/en-US/firefox/addon/sticky-notes/versions/0.10.24
