### ISSUE TITLE
Migrate to web extension

### ISSUE THREAD

**Issue by kumabook** [kumabook/stickynotes#78]
Need to use web extension by the end of 2017

https://blog.mozilla.org/addons/2016/11/23/add-ons-in-2017/

There are some problem

1 sidebar: web-extension doesn't provide sidebar
2 preference window: web-extension doesn't provide xul window
3 database: migrate sqlite to indexDb

**Comment by zendre4** [comment]
But they are a big advantage,:

- Compatibility with other browser 

The sidebar is very well but if the extension have a good backend it's okay too.

**Comment by kumabook** [comment]
Sidebar is now supported : https://developer.mozilla.org/en-US/Add-ons/WebExtensions/manifest.json/sidebar_action

So, The time for migration has come.
That will be 3 step.

1. migrate to hybrid extension
- only ui (sidebar, menu ui, content_scripts)

2. data migrate with hybrid extension
- from sqlite to indexedDB

3. completely web extension

The dead line is 2017/11.

So,  
Step 1 (2017/5
Step 2 (2017/7
Step 3 (2017/11

**Comment by zendre4** [comment]
If it possible extension for Chromium/Goolge Chrome, would be very great !  
This will attract many people...

**Comment by zendre4** [comment]
Any news ?

**Comment by kumabook** [comment]
Sorry, still working.

**Comment by kumabook** [comment]
Now, hybrid version(0.11.2) is still in review.

**Comment by kumabook** [comment]
hybrid version 0.11.2 isn't approved yet.
So, I submitted full webextension version (1.0.0).
It is approved
https://addons.mozilla.org/en-US/firefox/addon/sticky-notes/versions/1.0.0

**Comment by zendre4** [comment]
Hello, working for me but I have a bug with the sidebar... I Have close the sidebar and now I can't open it !

**Comment by kumabook** [comment]
sidebar open bug is fixed at #89

**Comment by kumabook** [comment]
release as version 1.0.1 
https://addons.mozilla.org/ja/firefox/addon/sticky-notes/versions/1.0.1

**Comment by kumabook** [comment]
Uploaded 0.11.1 on https://github.com/kumabook/stickynotes/releases/tag/0.11.1

**Comment by zendre4** [comment]
Thanks, it works !
