### ISSUE TITLE
Backend not working

### ISSUE THREAD

**Issue by zendre4** [kumabook/stickynotes#83]
Hello, 

I have remark than the backend not working : 

![image](https://cloud.githubusercontent.com/assets/9673982/23705927/4979b458-040c-11e7-9d86-1ba69d232f61.png)

I  can't either logon ...

**Comment by kumabook** [comment]
Thank for reporting!
I just fixed it.

**Comment by zendre4** [comment]
Thanks !

**Comment by kumabook** [comment]
Fixed with https://github.com/kumabook/stickynotes-backend/pull/6
