### ISSUE TITLE
Function to clear cache 

### ISSUE THREAD

**Issue by zendre4** [kumabook/stickynotes#88]
Hello,

Sometimes I have a problem of synchronization on my computers (exemple deleted stickies in computer A wasn't deleted in computer B). For fix this issues in the past extension (before web extension) I would delete the sqlLight database in local and I restart firefox... But with the new web extension it's not possible, so I think than the best solution is add in menu a link for deleted local cache and re-sync ...

What do you think ?

**Comment by kumabook** [comment]
First, webextension can't use sqlite. So new version uses indexedDB.
I think indexedDB isn't vislbe in file system.
I also think `Clear cache` is good way.
I will implement it, please wait

**Comment by kumabook** [comment]
And I will fix synchronization problem too.

**Comment by zendre4** [comment]
Thanks !

**Comment by kumabook** [comment]
release as version 1.0.1 
https://addons.mozilla.org/ja/firefox/addon/sticky-notes/versions/1.0.1

**Comment by zendre4** [comment]
Thanks ! working for me
