### ISSUE TITLE
Loss of data when creating and editing note.

### ISSUE THREAD

**Issue by radjah** [kumabook/stickynotes#94]
1. Create new note
1. Write something
1. Add tags
1. Write some tags
1. Press "Done" or Enter

Result: empty note with tags

1. Create new note
1. Add tags
1. Write some tags
1. Press "Done" or Enter
1. Write something

Result: your note with tags

1. Open page with note
1. Add tags
1. Write some tags
1. Press "Done" or Enter

Result: empty note with tags

**Comment by kumabook** [comment]
Hi! thank you for your reporting!

I fixed it and it is released as [1.1.1](https://addons.mozilla.org/ja/firefox/addon/sticky-notes/versions/?page=1#version-1.1.1)

Please check it out.

Thanks
